### PR TITLE
Adding support for depccg parser

### PR DESCRIPTION
**Pull request by shanest**
Hi Hai Hu,

For part of a pipeline I'm working on, I wanted to use your calculator with another parser, depccg (https://github.com/masashi-y/depccg).  I made some small work-arounds to get it to work.  The only thing I'm not positive about is pass2act; The only repo I could find with anything like that no longer works the way your code does, so I made some modifications to preprocess.py.  Now, everything works for me at least!  Let me know what you think.

### CODE REVIEW

**Comment by huhailinguist** [comment]
Hi Shane! Thanks for your interest in this. I just cleaned up the whole repository before I saw your pull request! Sorry about this but I will merge your code!

- pass2act: I now removed the pass2act part in preprocessing because I think not everyone needs that conversion. 

- depccg: I will look into your code. In fact, I talked to the author of depccg a long time ago, asking if he would be interested to retrain his model on the rebanked ccg. The problem is: the tree for relative clauses in the original CCGbank is off. So any parser trained on the original CCGbank will give wrong parses for relative clauses. However, the rebanked CCG corrected this, so ideally we want to use the rebanked CCG as training data for depccg. 

In theory, ccg2mono can use any parser output, as long as it is translated into the tree structure I defined, which involves reading txt/html output of the parser and "feeding" it to my structure. I will see how to do this and let you know!

**Comment by huhailinguist** [comment]
Hello, I added the capability to read from depccg. Could you re-clone the repo and try? The way you tried it would be problematic b/c that particular output format from depccg doesn't have info about the rules used in each step. I changed to xml output format.

**Comment by shanest** [comment]
Hi Hai,

Thanks for doing this!  Your integration with depccg works very well for
me, and thank you for the improved README and output of .tokenized files as
well :).

Let me mention a few small linguistic things I encountered when trying to
run this on various corpora, and let me know what you think.  I'm also
happy to make a new PR with some of them if that's easier.

(1) 'these', 'those': I put these in with 'both', 'neither', 'the', in
CCGTree.markLeaftNodes in getMono.  I saw that you had a comment about
'this', and 'that'; I guess they should also go there?

(2) I added 'ANY' with semCat.marking and semCat.OUT.marking as '+'.  This
seemed to give the right results.

(3) 'None of the': This is an issue with depccg, but I noticed that 'None'
always gets labeled as a bare N, so it's hard to make it negative and have
negative polarity in, e.g. "none of the students came to class."  Or am I
missing something?

At any rate, like I said, I'm happy to make a new PR with (1) and (2) if
that's easiest, but thought I'd ask you while I have your attention just to
make sure I understand the system right.  And thanks again for the smooth
integration with depccg!

**Comment by huhailinguist** [comment]
Hi Shane,

(1) I think you are right in this observation. So I put THESE, THOSE, THIS, THAT with MOST, assuming they are only upward on the second argument. 

(2) We thought about "any" before, but it is a complicated story b/c there are different "ANY"s. 

Anyone can do elementary school math. (any=every)
He didn't telll anyone. (something different, but we are not sure what to do with it)

If you have any suggestions, please let us know or you can do another pull request. :) 

(3) You can first check the visualized output to see if the CCG parse is wrong. I doubt if the parser can do this correctly....

I think I merged most of your changes. I kept your modification about "ANY", but it may not be ideal. 

I tested again; everything is still working. One suggestion though, easyccg gets the relative clauses correct, so if you have a lot of relative clauses, it's better to use easyccg. 

Although depccg is doing better on benchmarks, you may want to look at the actual parses of your data to decide which parser to use.

**Comment by shanest** [comment]
Hi Hai,

Thanks!

Re (2): indeed, it's a very complicated case.  For my current application,
all the sentences are generated in such a way that I know the +/+ behavior
is correct, but indeed it's subtle.  I'll think more about this in the
future.

Re (3): right, I was reporting that the parser assigns NN to "None", and so
it's not clear that polarity can get attached in the way one wants at all.
And I did find this issue by looking at the output parses, which are
otherwise pretty good.  One question: the NN becomes an NP via "lex" rule;
this is then an argument to the "of the X" of type NP/NP.  (See below for
an example.). I thought assigning "None" a "-" marking would do the trick,
but it appears not to have.

[image: Screen Shot 2019-10-29 at 11.04.36 AM.png]

**Comment by huhailinguist** [comment]
Hi Shane,

Re (2): it's indeed pretty complicated, but if all the "any" in your data is the same "any", then feel free to set the +/- markings as it suits your needs.

Re (3): what is your scenario here? Is it only "None of the" + noun and no other structures involving "none"? If that's the case, you could replace "none of the" with "no" in preprocessing? I have implemented some mechanism to do this in the code. If you don't need it urgently I can probably do it over the weekend. 

I talked to Larry yesterday about  your interests in our code and our conversation. He was very excited about it. Maybe it's time to move to emails.. I will send an email to both of you.

**Pull request merged**
